### ISSUE TITLE
Please give a Makefile of LiBrotherClientBackend for g++

### ISSUE THREAD

**Issue by croissantfish** [sxtyzhangzk/LiBrother#1]
Hi, I'm your TA. I think you need to add a Makefile of LiBrotherClientBackend. I know it is a VC project but there is a big problem. After I uninstall my VS2013 from my windows 10, there is not a avaliable version of Qt for VS2015. So I have to test your project in Ubuntu. Because of this, you should provide a Makefile for Ubuntu 15.10(amd64) and g++-5.2.1.

**Comment by j96w** [comment]
Hi TA,i think zzk will soon give you response.thank you.

**Comment by sxtyzhangzk** [comment]
The CMakeLists.txt has been written into release/librother-1.0-release-src.zip , you may need CMake to build the project.
